### ISSUE TITLE
Don't know how to build task 'index:measurements'

### ISSUE THREAD

**Issue by fortiko** [HabitatMap/AirCasting#8]
Thanks for this fantastic piece of work!

I just stumbled onto something, and I am not sure how to proceed: After installing elastic search, one is supposed to run the following command to create the necessary indices which clearly don't work for me when run from the install dir:

```
~/aircasting$ rake index:measurements
~/.rvm/gems/ruby-2.0.0-p648/gems/activesupport-3.2.22/lib/active_support/testing/mochaing.rb:5: warning: already initialized constant Mocha
~/.rvm/gems/ruby-2.0.0-p648/gems/mocha-0.10.5/lib/mocha/version.rb:1: warning: previous definition of Mocha was here
rake aborted!
Don't know how to build task 'index:measurements'
~/.rvm/gems/ruby-2.0.0-p648/bin/ruby_executable_hooks:15:in `eval'
~/.rvm/gems/ruby-2.0.0-p648/bin/ruby_executable_hooks:15:in `<main>'
```

and this in turn then leads to the following error ("missing index") when trying to open the CrowdMap:

```
[1d1a1fcf679a63c257b3905301f67304]   Elastic::Measurement Search (9.8ms) {index: "particulate_matter_airbeam_pm", type: "measurement", body: {"query"=>{"filtered"=>{"filter"=>{"and"=>{"filters"=>[{"terms"=>{"stream_id"=>[]}}, {"range"=>{"day_of_year"=>{"gte"=>0, "lte"=>365}}}, {"range"=>{"year"=>{"gte"=>2015, "lte"=>2016}}}, {"or"=>{"filters"=>[{"range"=>{"minutes_of_day"=>{"gte"=>1380}}}, {"range"=>{"minutes_of_day"=>{"lte"=>1379}}}]}}]}}}}, "_source"=>false, "size"=>100, "aggs"=>{"middle_x"=>{"terms"=>{"size"=>100, "script"=>"round(doc['longitude'].value / 7.463538128396739e-05)"}, "aggs"=>{"middle_y"=>{"terms"=>{"size"=>100, "script"=>"round(doc['latitude'].value / 6.62473726694923e-05)"}, "aggs"=>{"avg_value"=>{"avg"=>{"field"=>"value"}}}}}}}}}
[1d1a1fcf679a63c257b3905301f67304] Completed 500 Internal Server Error in 18.0ms
[1d1a1fcf679a63c257b3905301f67304]
Elasticsearch::Transport::Transport::Errors::NotFound ([404] {"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index","index":"particulate_matter_airbeam_pm","resource.type":"index_or_alias","resource.id":"particulate_matter_airbeam_pm"}],"type":"index_not_found_exception","reason":"no such index","index":"particulate_matter_airbeam_pm","resource.type":"index_or_alias","resource.id":"particulate_matter_airbeam_pm"},"status":404}):
  lib/elastic/average_info.rb:97:in `aggregations'
  lib/elastic/average_info.rb:37:in `measurements'
  lib/elastic/average_info.rb:23:in `averages'
  lib/elastic/average_info.rb:17:in `as_json'
  app/controllers/api/averages_controller.rb:53:in `index'
```

Could you please explain where the task is defined? Thanks again!

**Comment by szemek** [comment]
Hello @fortiko 
sorry for this issue, I updated [documentation for ElasticSearch](https://github.com/HabitatMap/AirCasting/blob/master/doc/elasticsearch.md)
The difference is that you need to run `rake elastic:index:measurements` instead of what you have typed before. Task responsible for indexing is defined in [lib/tasks/elastic/index.rake](https://github.com/HabitatMap/AirCasting/blob/master/lib/tasks/elastic/index.rake) file.

Kind regards,
Przemysław

**Comment by fortiko** [comment]
Great, thank you for pointing that out. The indexes now get created, yet I am still unable to see any data (that is in the MySQL DB) on the web interface as pointed out here: https://github.com/HabitatMap/AirCasting/issues/9
